#!/usr/bin/env python3
"""Generate golden protocol vectors for weread-core Lua tests.

The Python reference implementation in
apps/koreader-plugin/scripts/fetch_weread_epub.py is the protocol oracle.
This script emits a Lua table consumed by tests/spec/protocol_golden_spec.lua
so the Lua port is diff-tested against the oracle on every run.

Note: weread_e() semantics intentionally cover ASCII inputs only. The real
call sites only feed ASCII (book ids, chapter uids, timestamps); non-ASCII
would diverge between Python (code points) and Lua (bytes).
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", ".."))
sys.path.insert(0, os.path.join(REPO, "apps", "koreader-plugin", "scripts"))

import fetch_weread_epub as oracle  # noqa: E402

E_INPUTS = [
    "1",
    "0",
    "1700000000",
    "3300012345",
    "123456789012",
    "a38237c0730a1b2c3d4e5f6",
    "MP_WXS_1234567890",
]

SIGN_PARAMS = [
    {"ct": "1700000000", "st": 0},
    {
        "b": oracle.weread_e("3300012345"),
        "c": oracle.weread_e("17"),
        "r": "15239929",
        "ct": "1700000000",
        "ps": "fakepsvtsvalue",
        "pc": oracle.weread_e("1700000000"),
        "sc": 1,
        "prevChapter": False,
        "st": 0,
    },
    {
        "b": oracle.weread_e("MP_WXS_1234567890"),
        "c": oracle.weread_e("3"),
        "r": "987654",
        "ct": "1700000123",
        "ps": "anotherpsvts",
        "pc": oracle.weread_e("1700000123"),
        "sc": 2,
        "prevChapter": True,
        "st": 1,
    },
]

MD5_INPUTS = [
    "",
    "hello",
    "a" * 64,
    "微信读书",  # utf-8 multibyte
]


def lua_str(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def lua_value(value) -> str:
    if value is True:
        return "true"
    if value is False:
        return "false"
    if isinstance(value, str):
        return lua_str(value)
    return repr(value)


def main() -> None:
    out = [
        "-- GENERATED by tools/fixtures/gen_protocol_vectors.py; do not edit.",
        "-- Regenerate: python3 tools/fixtures/gen_protocol_vectors.py > tests/fixtures/protocol_vectors.lua",
        "return {",
        "    e = {",
    ]
    for value in E_INPUTS:
        out.append(f"        {{ input = {lua_str(value)}, want = {lua_str(oracle.weread_e(value))} }},")
    out += [
        "    },",
        "    sign = {",
    ]
    for params in SIGN_PARAMS:
        query = oracle.sorted_query(params)
        sig = oracle.weread_sign(query)
        entries = ", ".join(f"{k} = {lua_value(v)}" for k, v in sorted(params.items()))
        out.append(
            f"        {{ params = {{ {entries} }}, want_query = {lua_str(query)}, want_sign = {lua_str(sig)} }},"
        )
    out += [
        "    },",
        "    md5 = {",
    ]
    for value in MD5_INPUTS:
        out.append(f"        {{ input = {lua_str(value)}, want = {lua_str(oracle.md5_hex(value))} }},")
    out += [
        "    },",
        "}",
        "",
    ]
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main()
