#!/usr/bin/env python3
"""Regenerate the QR golden fixtures (tests/fixtures/qr_matrices.lua).

Uses pyqrcode as the oracle (byte mode, ECC level M, automatic mask).
segno is NOT a suitable oracle: its write_padding_bits adds 8 - (len % 8)
zero bits unconditionally, inserting a spurious 0x00 codeword when the
stream already ends on a codeword boundary (non-conformant with
ISO/IEC 18004 §7.4.10; decoders tolerate it, byte-diffing does not).
"""

import pyqrcode

TEXTS = [
    "HELLO",
    "https://weread.qq.com/web/confirm?uid=3f9a8b2c7d1e",
    "https://weread.qq.com/web/confirm?uid=abcdef1234567890abcdef1234567890abcd",
    "The quick brown fox jumps over the lazy dog. 0123456789",
]


def main():
    out = [
        "-- GENERATED by tools/fixtures/gen_qr_fixtures.py (pyqrcode oracle). Do not edit.",
        "return {",
    ]
    for text in TEXTS:
        qr = pyqrcode.create(text.encode(), error="M", version=None, mode="binary")
        out.append("    {")
        out.append('        text = "' + text.replace('"', '\\"') + '",')
        out.append("        matrix = {")
        for row in qr.code:
            out.append('            "' + "".join("1" if c else "0" for c in row) + '",')
        out.append("        },")
        out.append("    },")
    out.append("}")
    out.append("")
    print("\n".join(out))


if __name__ == "__main__":
    main()
