#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 32
#define LV_USE_STDLIB_MALLOC    LV_STDLIB_MALLOC_BUILTIN
#define LV_USE_STDLIB_STRING    LV_STDLIB_STRING_BUILTIN
#define LV_USE_STDLIB_SPRINTF   LV_STDLIB_SPRINTF_BUILTIN
#define LV_MEM_SIZE (64 * 1024U)

#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_LOG_PRINTF 1

#define LV_USE_SDL 1
#define LV_USE_OS LV_OS_NONE

#define LV_FONT_MONTSERRAT_14 1
#define LV_FONT_MONTSERRAT_20 1
#define LV_FONT_MONTSERRAT_28 1
#define LV_FONT_DEFAULT &lv_font_montserrat_20

#define LV_USE_CANVAS 1
#define LV_USE_LABEL 1
#define LV_USE_BUTTON 1
#define LV_USE_LIST 1
#define LV_USE_IMAGE 1
#define LV_USE_IMG 1
#define LV_USE_TEXTAREA 1

#endif

#define LV_USE_FREETYPE 1
