-- GENERATED by tools/fixtures/gen_protocol_vectors.py; do not edit.
-- Regenerate: python3 tools/fixtures/gen_protocol_vectors.py > tests/fixtures/protocol_vectors.lua
return {
    e = {
        { input = "1", want = "c4c329b011c4ca4238a0201" },
        { input = "0", want = "cfc32da010cfcd208495488" },
        { input = "1700000000", want = "24932c107a21fe80g010f72" },
        { input = "3300012345", want = "1d6322f0813ab6b52g015239" },
        { input = "123456789012", want = "341326f0775bcd15g01c007" },
        { input = "a38237c0730a1b2c3d4e5f6", want = "1e342fc2e613338323337633037333061316232633364346535663697d" },
        { input = "MP_WXS_1234567890", want = "5ca4266224d505f5758535f313233343536373839300c3" },
    },
    sign = {
        { params = { ct = "1700000000", st = 0 }, want_query = "ct=1700000000&st=0", want_sign = "2b33d4d0" },
        { params = { b = "1d6322f0813ab6b52g015239", c = "70e32fb021170efdf2eca12", ct = "1700000000", pc = "24932c107a21fe80g010f72", prevChapter = false, ps = "fakepsvtsvalue", r = "15239929", sc = 1, st = 0 }, want_query = "b=1d6322f0813ab6b52g015239&c=70e32fb021170efdf2eca12&ct=1700000000&pc=24932c107a21fe80g010f72&prevChapter=false&ps=fakepsvtsvalue&r=15239929&sc=1&st=0", want_sign = "dd5c1bbe" },
        { params = { b = "5ca4266224d505f5758535f313233343536373839300c3", c = "ecc32f3013eccbc87e4b62e", ct = "1700000123", pc = "782320307a21fe8cg013826", prevChapter = true, ps = "anotherpsvts", r = "987654", sc = 2, st = 1 }, want_query = "b=5ca4266224d505f5758535f313233343536373839300c3&c=ecc32f3013eccbc87e4b62e&ct=1700000123&pc=782320307a21fe8cg013826&prevChapter=true&ps=anotherpsvts&r=987654&sc=2&st=1", want_sign = "5c45a09e" },
    },
    md5 = {
        { input = "", want = "d41d8cd98f00b204e9800998ecf8427e" },
        { input = "hello", want = "5d41402abc4b2a76b9719d911017c592" },
        { input = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", want = "014842d480b571495a4a0363793f7367" },
        { input = "微信读书", want = "664b5d039b78fe3d81097e9977924823" },
    },
}
