-- Golden tests: weread-core protocol/crypto vs the Python reference oracle.
-- Vectors are generated by tools/fixtures/gen_protocol_vectors.py from
-- apps/koreader-plugin/scripts/fetch_weread_epub.py. Run via tests/run_all.sh.

local Protocol = require("weread.lib.protocol")
local Crypto = require("weread.lib.crypto")
local vectors = dofile("tests/fixtures/protocol_vectors.lua")

local failures, checks = 0, 0

local function eq(got, want, label)
    checks = checks + 1
    if got ~= want then
        failures = failures + 1
        print(string.format("FAIL %s:\n  got  %s\n  want %s", label, tostring(got), tostring(want)))
    end
end

for _, v in ipairs(vectors.e) do
    eq(Protocol.e(v.input), v.want, "e(" .. v.input .. ")")
end

for _, v in ipairs(vectors.sign) do
    eq(Protocol.sorted_query(v.params), v.want_query, "sorted_query")
    eq(Protocol.sign(v.want_query), v.want_sign, "sign")
end

for _, v in ipairs(vectors.md5) do
    eq(Crypto.md5_hex(v.input), v.want, "md5_hex(#" .. #v.input .. ")")
end

print(string.format("protocol_golden_spec: %d checks, %d failure(s)", checks, failures))
if failures > 0 then
    os.exit(1)
end
